name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: neilpeterson/action-create-blueprint@v1.0.0.0-alpha
    - name: Create Azure Blueprint
      env:
        SUBSCRIPTIONID: 0dcde382-dac2-44d0-b746-1e0bf404c20f
        BLUEPRINTPATH: ./infrastructure
        BLUEPRINTNAME: testBluePrint
        SPNID: 35670f35-bbb7-4d20-b8e0-8ca76c4e008c
        SPNPASS: ${{ secrets.spnPass }}
        TENANTID: eb73c9bc-7f90-4841-9556-c3a56cc82c79
        MGID: charotmg
      run: ./00-importBlueprint.ps1
      shell: pwsh
    - name: Publish the blueprint
      env:
        SUBSCRIPTIONID: 0dcde382-dac2-44d0-b746-1e0bf404c20f
        BLUEPRINTPATH: ./infrastructure
        BLUEPRINTNAME: testBluePrint
        SPNID: 35670f35-bbb7-4d20-b8e0-8ca76c4e008c
        SPNPASS: ${{ secrets.spnPass }}
        TENANTID: c10899d7-fac0-4b82-98f4-e89021fb4476
        VERSION: 2.0.0
        MGID: Blueprints
      run: ./01-publishBlueprint.ps1
      shell: pwsh
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Assign the blueprint
      env:
        SUBSCRIPTIONID: 0dcde382-dac2-44d0-b746-1e0bf404c20f
        ASSIGNMENTFILE: ./infrastructure/assign.json
        BLUEPRINTNAME: testBluePrint
        SPNID: 35670f35-bbb7-4d20-b8e0-8ca76c4e008c
        SPNPASS: ${{ secrets.spnPass }}
        TENANTID: c10899d7-fac0-4b82-98f4-e89021fb4476
        VERSION: 1.0.0
      run: ./02-assignBlueprint.ps1
      shell: pwsh
