name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Create Azure Blueprint
      uses: neilpeterson/action-create-blueprint@master
      env:
        AZURETENANTID: ${{ secrets.AZURETENANTID }}
        AZURECLIENTID: ${{ secrets.AZURECLIENTID }}
        AZUREPASSWORD: ${{ secrets.AZUREPASSWORD }}
      with:
        azureManagementGroupName: Blueprints
        blueprintName: GH-Actions-test
        blueprintPath: ./create
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Assign Azure Blueprint
      uses: neilpeterson/action-assign-blueprint@master
      env:
        AZURETENANTID: ${{ secrets.AZURETENANTID }}
        AZUREPASSWORD: ${{ secrets.AZUREPASSWORD }}
        AZURECLIENTID: ${{ secrets.AZURECLIENTID }}
      with:
        AssignmentName: GH-Action-BlueprintPublish
        azureManagementGroupName: Blueprints
        blueprintName: GH-Actions-test
        azureSubscriptionID: 00000000-0000-0000-0000-000000000000
        AssignmentFilePath: ./assign/assign-blueprint.json
